Vagrant.configure("2") do |config|
	#box
  config.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
	@piton
  config.vm.define "piton" do |up|
    up.vm.provision "shell", inline:"/vagrant/pre-install.sh"    
    up.vm.network "private_network", ip: "192.168.56.22"         
  end
end

